FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim as base
WORKDIR /app

EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.1-stretch as build
WORKDIR /src

COPY ./appscore .

WORKDIR /src/Web

RUN dotnet restore Web.csproj && \
  dotnet build Web.csproj -c Release -o /app/build

FROM build as publish

RUN dotnet publish Web.csproj -c Release -o /app/publish

FROM base as final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Web.dll"]